name: Docker Workflow

on:
  push:
  - branch: main
  workflow_dispatch: 

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: virtualr

jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Docker Build
      run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .

    - name: Docker Login
      run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Publish 
      run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  docker_deploy:
    needs: docker_build
    concurrency: 
      group: production-deployment
      cancel-in-progress: true
    runs-on: ubuntu-latest 
    steps:
      - name: Docker Login
        run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker Run
        run: |
          docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          sleep 300s